services:

  db:
    build: ./myapp/etl
    container_name: pulse_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_pass
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pulse_user -d pulse']
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: ./myapp/etl
    container_name: pulse_etl
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pulse
      DB_USER: pulse_user
      DB_PASSWORD: pulse_pass
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
